# Copy this file and name it "config.yaml"

redmine:
  url: ${REDMINE_URL}
  version: ${REDMINE_VERSION}
  api_key: ${REDMINE_API_KEY}
  time_zone: "Europe/Berlin"
  no_bot_tag: "#nobot" # a tag that signals bot not to handle an issue

actions:

  waiting_for_feedback:
    start_date: "2021-01-01"  # Date from which tickets are to be processed (all tickets from yyyy-mm-dd)
    time_range: "14"  # Number of days that should be exceeded without updates on the ticket
    projects:
      - "IT Tickets"  # List of redmine projects
    status:
      - "Waiting for feedback"  # List of all issue status you want to treat
    close_ticket: true  # Should the ticket be closed after the update?
    template: "close_ticket" # Template for the update massage

  in_revision:
    start_date: "2021-01-01"
    time_range: "14"
    projects:
      - "IT Tickets"
    status:
      - "In revision"
    change_status_to: 4
    template: "nudge_ticket"


logging:
  level: "ERROR"
